### ISSUE TITLE
Traceback: ImportError: cannot import name 'ImageQt' from 'PIL'

### ISSUE THREAD

**Issue by hunter86bg** [biqqles/wingman#37]
When trying to execute it always tracebacks:

```
Traceback (most recent call last):
  File "/home/snikolov/.local/bin/wingman", line 33, in <module>
    sys.exit(load_entry_point('wingman==5.1', 'gui_scripts', 'wingman')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snikolov/.local/bin/wingman", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/snikolov/.local/lib/python3.11/site-packages/wingman/__init__.py", line 34, in <module>
    from . import namespaces
  File "/home/snikolov/.local/lib/python3.11/site-packages/wingman/namespaces.py", line 28, in <module>
    from PIL import Image, ImageQt
ImportError: cannot import name 'ImageQt' from 'PIL' (/usr/lib64/python3.11/site-packages/PIL/__init__.py)
```

Any idea why it's failing to find the module ?
OS: Fedore 38
Arch: x86_64

**Comment by donteatyellowsno** [comment]
try this: `pip install PyQt6`
if you look in the imageqt.py thing you find there is before defining the imageqt class a check on if you have a certain qt package installed. they appearently removed qt5 packages which sucks for older projects
